layout_spectrum: 0.9401349
favicon: null
name: achims
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  bucket: null
  version: null
  domain: null
color:
  brandStrength: 0.8929174
  lightness: 0.1424958
  saturation: 0.2268128
  rhythmicContrast: 0
  brandColors:
    - '#D6E7FB'
    - '#0C0B0E'
    - '#C6BCBE'
    - '#81776D'
    - '#5C4B4B'
typography_spectrum: 0.6821248
