layout_spectrum: 0.7244277785066515
typography_spectrum: 0.41934403660707176
color:
  brandStrength: 0.9363094407599419
  lightness: 0.5062055934686214
  saturation: 0.9546781769022346
  rhythmicContrast: 0.7697293739765882
  brandColors:
    - '#105B63'
    - '#FFFAD5'
    - '#FFD34E'
    - '#DB9E36'
    - '#BD4932'
title: Achim Schulz
cta:
  domain: null
  version: null
  bucket: null
favicon: null
name: achimschulz
purpose: []
analytics:
  facebook: null
  google: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
