typography_spectrum: 0.4193440366070718
color:
  brandStrength: 0.9363094407599419
  saturation: 0.9546781769022346
  brandColors:
    - '#105B63'
    - '#FFFAD5'
    - '#FFD34E'
    - '#DB9E36'
    - '#BD4932'
  lightness: 0.5062055934686214
  rhythmicContrast: 0.7697293739765882
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.08072591
analytics:
  twitter: null
  google: null
  facebook: null
name: achimschulz
cta:
  bucket: null
  version: null
  domain: null
favicon: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: achimschulz
purpose: []
