layout_spectrum: 0.06661046
favicon: null
name: achims
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  version: null
  bucket: null
  domain: null
color:
  brandStrength: 0
  saturation: 0
  brandColors:
    - '#161720'
    - '#BB9A6F'
    - '#3A395B'
    - '#771627'
    - '#DAE1F0'
  lightness: 0
  rhythmicContrast: 0.5
typography_spectrum: 0.6821248
