name: achims
favicon: null
layout_spectrum: 0.12249
typography_spectrum: 0.17642
title: Achim Schulz
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8c837c'
    - '#a5b7c3'
    - '#17161b'
    - '#ffdb61'
    - '#985619'
  brandStrength: 0.1875
  lightness: 0.75
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
