color:
  brandStrength: 0.125
  saturation: 0.4374218
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#b5bec1'
    - '#4f616d'
    - '#ff6500'
  lightness: 0.625
  rhythmicContrast: 0.25
title: Achim Schulz
analytics:
  twitter: null
  google: null
  facebook: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  bucket: null
  version: null
  domain: null
favicon: null
layout_spectrum: 0.7415519
purpose: []
name: achimschulz
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.39161
