color:
  brandStrength: 0.125
  saturation: 0.8288364
  brandColors:
    - '#019201'
    - '#de0101'
    - '#90e697'
    - '#883601'
    - '#ffebe7'
  lightness: 0.5
  rhythmicContrast: 0.5961214
analytics:
  twitter: null
  google: null
  facebook: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  version: null
  bucket: null
  domain: null
favicon: null
layout_spectrum: 0.07335582
purpose: []
name: achims
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.17642
