name: achims
favicon: null
layout_spectrum: 0.13159
typography_spectrum: 0.17642
title: Achim Schulz
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e1f3fd'
    - '#bba57e'
    - '#51300f'
    - '#a3865e'
    - '#29170d'
  brandStrength: 0.125
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
