name: achims
favicon: null
layout_spectrum: 0.13159
typography_spectrum: 0.17642
title: Achim Schulz
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfadb'
    - '#07050a'
    - '#e7dfb1'
    - '#655d6c'
    - '#ba9a68'
  brandStrength: 0
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
