title: Achim Schulz
cta:
  domain: null
  version: null
  bucket: null
layout_spectrum: 0.1871089
favicon: null
name: achimschulz
purpose: []
analytics:
  facebook: null
  google: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.1921151
  lightness: 0.597622
  saturation: 0.5112641
  rhythmicContrast: 0.5951189
  brandColors:
    - '#00213E'
    - '#562F08'
    - '#DC5E0C'
    - '#284C6C'
    - '#F9D08D'
typography_spectrum: 0.39161
